.Dd November 28, 2025
.Dt GENICNS 1
.Os
.Sh NAME
.Nm genicns
.Nd Generate ICNS file from image file
.Sh SYNOPSIS
.Nm genicns
.Op Fl hlsv
.Op Fl o Ar file
.Op Ar file ...
.Sh DESCRIPTION
.Nm
is a simple command-line tool that generate ICNS file.
.Pp
Supported options:
.Bl -tag -width Ds
.It Fl o Ar file , Fl Fl output Ar file
Specify the name of the output file
.It Fl s , Fl Fl strip
Strip all metadata (ImageMagick is required)
.It Fl l , Fl Fl leave
Leave .iconset directory
.It Fl h , Fl Fl help
Display help message
.It Fl v , Fl Fl version
Display version information
.El
.Sh FILE FORMATS
.Nm
supports many file formats using some different commands.
.Bl -tag -width Ds
.It PNG
Native support
.It SVG
Inkscape is required
.It Other image formats
ImageMagick is required
.El
